### ISSUE TITLE
mac  can't run 

### ISSUE THREAD

**Issue by S-arige** [wax8280/web2kindle#3]
➜  web2kindle-master python main.py zhihu_daily          
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from web2kindle.script import zhihu_collection_main, zhihu_zhuanlan_main, zhihu_answers_main, guoke_scientific_main, \
  File "/Users/xxx/Downloads/web2kindle-master/web2kindle/__init__.py", line 7, in <module>
    from web2kindle.libs.utils import load_config
  File "/Users/xxx/Downloads/web2kindle-master/web2kindle/libs/utils.py", line 145
    def get_next_datetime_string(data_string: str, format_string: str, days: int, prev=False) -> str:
                                            ^
SyntaxError: invalid syntax

**Comment by wax8280** [comment]
1.需要Python3。暂不支持Python2。
2.确保代码是最新的。

**Comment by S-arige** [comment]
谢谢，是使用lpython2导致的
